### ISSUE TITLE
in the latest version for the mod

### ISSUE THREAD

**Issue by CharCharthemonkey** [ArtixAllMighty/Rpg-Addon-UmbraLux#2]
same as the beastmaster mod the armors for necromancer mage archer paladin and berserker do not show recipes at all for armors and some weapons also the advanced bow does not work with arrows at all

**Comment by AbsolemJackdaw** [comment]
that's rather problematic ._. 
how come noone else ever reported this to me ? 
I'll be looking into it tomorrow. Meanwhile, you can edit the recipe json's yourself to fix the temporary problem for armor.

**Comment by CharCharthemonkey** [comment]
well honestly no1 really uses the mods from wat ive seen so yea but i do use them and am seeing the issues lol

**Comment by AbsolemJackdaw** [comment]
are you sure you got the latest version ? 
the last release dates from 25 august 2017, and the recipes haven't been tocuhed since 27 july 2017.
the recipes are working just fine 

![](http://i.imgur.com/lZkn2yH.png)

**Comment by AbsolemJackdaw** [comment]
and the arrows are working fine as well ? 

demonstrating a regular shot on the tree (bottom left), and the side way shot on the leaves, top left
![](http://i.imgur.com/Spx1fmB.png)

are you sure you are wearing the full armor when using the advanced bow ?

**Comment by AbsolemJackdaw** [comment]
I'm taking back the firing arrows. 
testing in forge vanilla, non-dev environement, the arrows are pretty messed up

**Comment by CharCharthemonkey** [comment]
the armor recipes do not show and yes its the latest version for 1.12 atleast latest as far as wats on the app so yea and i tried the adv bow and nothing worked nor did it say on the wiki that ud need full armor for it to work

**Comment by CharCharthemonkey** [comment]
the armor recipes do not show and yes its the latest version for 1.12 atleast latest as far as wats on the app so yea and i tried the adv bow and nothing worked nor did it say on the wiki that ud need full armor for it to work
![2017-08-29_11 45 59](https://user-images.githubusercontent.com/30783285/29833074-d6897b86-8caf-11e7-8979-7f07c88db421.png)
![2017-08-29_11 45 53](https://user-images.githubusercontent.com/30783285/29833087-dea490b2-8caf-11e7-9e48-a561880193fc.png)
![2017-08-29_11 45 50](https://user-images.githubusercontent.com/30783285/29833094-e537f57c-8caf-11e7-8429-5265fcbc1f13.png)
![2017-08-29_11 45 24](https://user-images.githubusercontent.com/30783285/29833106-ece65598-8caf-11e7-8617-aeffba715524.png)
![2017-08-29_11 45 29](https://user-images.githubusercontent.com/30783285/29833126-fc36da0e-8caf-11e7-8291-70fff7f47fed.png)
![2017-08-29_11 45 31](https://user-images.githubusercontent.com/30783285/29833121-fc24e7cc-8caf-11e7-9436-d950a1865302.png)
![2017-08-29_11 45 32](https://user-images.githubusercontent.com/30783285/29833123-fc2ba54e-8caf-11e7-83ce-20e134a3ce21.png)
![2017-08-29_11 45 35](https://user-images.githubusercontent.com/30783285/29833124-fc2c282a-8caf-11e7-8cab-7b8e0c0ad9d7.png)
![2017-08-29_11 45 37](https://user-images.githubusercontent.com/30783285/29833122-fc2a2b2e-8caf-11e7-8652-5b7466f6f84e.png)
![2017-08-29_11 45 44](https://user-images.githubusercontent.com/30783285/29833125-fc2e5e2e-8caf-11e7-89a3-cebc67294a9a.png)
![2017-08-29_11 45 47](https://user-images.githubusercontent.com/30783285/29833127-fc70ee42-8caf-11e7-89cb-4f87c210ec53.png)
![2017-08-29_11 45 50](https://user-images.githubusercontent.com/30783285/29833128-fc9dc12e-8caf-11e7-8e77-4fa5306546d4.png)

**Comment by AbsolemJackdaw** [comment]
JEI not having the recipes doesn't mean it is uncraftable. I can craft armor pretty fine in my minecraft.
might be a JEI problem ? 
have you got a log for me ? maybe JEI doesn't like something in the json files that minecraft does support. 

Doesn't the wiki say you need armor to use the weapon ? all class weapons require the appropriate class armor to work. I'll double check the wiki on that info

meanwhile, try to double check the versions with the actual uploaded files on the site. you never know, maybe the app failed or something.

(rest assured, im currently on the problem)

**Comment by AbsolemJackdaw** [comment]
try moving the recipes.armor folder content to just recipes.
maybe JEI doesn't like subfolders ?

**Comment by CharCharthemonkey** [comment]
1 the wiki doesnt say the armors are needed 2 ty for working on it 3 its been like this since the beastmaster mod issue with the armors 4 they are the latest on the app as on the wiki 5 (sry if i seem rude or something not my intention) 6 could be a JEI issue idk how to tell on that part since other items show recipes fine 7 i will try moving the folder then let u know

**Comment by CharCharthemonkey** [comment]
i think ik wat happened im not even seeing a folder for recipes from any of the rpg mods at all so that might be y its not showing idk

**Comment by CharCharthemonkey** [comment]
[Charlies Adventure Pack 4-1.0.zip](https://github.com/ArtixAllMighty/Rpg-Addon-UmbraLux/files/1261113/Charlies.Adventure.Pack.4-1.0.zip)

theres my modpack im making if u wanna test that and maybe figure out wats causing it?

**Comment by AbsolemJackdaw** [comment]
the thing being that JEI isn't a proof that recipes don't work. 
try to craft the armor with one of the leathers, and it should be working.

oh ? no recipes at all ?
my copy of the mod, that i downloaded from curseforge website earlier today has the assets/umbralux/recipes/armor folder just fine. are you looking inside the .jar file ?

**Comment by CharCharthemonkey** [comment]
umm for looking in a jar file im gonna say no cause idk how to do that since my know how is limited at best on this lol and ill try the leather idea

**Comment by AbsolemJackdaw** [comment]
okay, downlaoded your pack, trying it now

**Comment by AbsolemJackdaw** [comment]
![](http://i.imgur.com/wfZQ4J4.png)

??

**Comment by AbsolemJackdaw** [comment]
neither one of them are for 1.12 ?

**Comment by CharCharthemonkey** [comment]
those were previous versions that failed miserably for my attempts to make good packs but the 1.12 version is my latest attempt

**Comment by AbsolemJackdaw** [comment]
ah okay. (still trying to figure out how modpacks work)

**Comment by CharCharthemonkey** [comment]
yea and figure out how to gate stuff behind other tech/magic mods too is tough

**Comment by AbsolemJackdaw** [comment]
okay how do I install this modpack before i throw my laptop out of the window ? xD

**Comment by AbsolemJackdaw** [comment]
ive unzipped it in a folder, then made a new launch configuration, pointing to that folder, including forge as release.
only 5 mods are loaded, which are the forge basic mods.

**Comment by CharCharthemonkey** [comment]
on the app click custom profile then import and it "should" work also this is not working 
![2017-08-29_13 00 43](https://user-images.githubusercontent.com/30783285/29836370-a95f27fe-8cba-11e7-8a6b-725f9bd6f1fd.png)
![2017-08-29_13 00 46](https://user-images.githubusercontent.com/30783285/29836371-a9620550-8cba-11e7-9ee6-e001e46357e9.png)
![2017-08-29_13 00 50](https://user-images.githubusercontent.com/30783285/29836372-a96512b8-8cba-11e7-909d-c55236b7b315.png)
![2017-08-29_13 00 55](https://user-images.githubusercontent.com/30783285/29836373-a969ae86-8cba-11e7-81cb-9b96c964018a.png)
![2017-08-29_13 02 09](https://user-images.githubusercontent.com/30783285/29836374-a96f9bd4-8cba-11e7-98e7-1ea11e429336.png)
![2017-08-29_13 02 28](https://user-images.githubusercontent.com/30783285/29836375-a97a8134-8cba-11e7-9c16-986a08436d61.png)
and note these are the same recipes as shown on the wiki which the sword the recipe is backwards and nothing else works at all even using the recipes from the wiki

**Comment by AbsolemJackdaw** [comment]
i installed the app but saw no such thing as import

**Comment by CharCharthemonkey** [comment]
u have to enable the minecraft side for the app under settings then minecraft then turn that on

**Comment by AbsolemJackdaw** [comment]
![](http://i.imgur.com/gBsqqR9.png)

doesnt let me point it to my install location

**Comment by CharCharthemonkey** [comment]
id report that to the twitch devs then

**Comment by AbsolemJackdaw** [comment]
because there are 'special characters'
which is .minecraft 
i mean ffs ? 

made another minecraft install directory
still dont see the import button

**Comment by AbsolemJackdaw** [comment]
![](http://i.imgur.com/hf6a88Q.png)

**Comment by CharCharthemonkey** [comment]
the import is under create custome profile 
![this](https://user-images.githubusercontent.com/30783285/29837209-2a6bbbd0-8cbd-11e7-80be-45c1aed6b79d.JPG)

**Comment by AbsolemJackdaw** [comment]
ooh ...

**Comment by AbsolemJackdaw** [comment]
![](http://i.imgur.com/Ts037Ym.png)

had downlaoded all mods

**Comment by CharCharthemonkey** [comment]
thats a known twitch issue and if u want i can give u the modlist to download them as it sits atm

**Comment by AbsolemJackdaw** [comment]
nah im good it works now =)

**Comment by CharCharthemonkey** [comment]
k

**Comment by CharCharthemonkey** [comment]
hopefully u can see the recipes not working lol and figure out y for me? since im out of reasons y

**Comment by AbsolemJackdaw** [comment]
Parsing error loading recipe umbralux:necromancer_skull
com.google.gson.JsonParseException: Missing data for item 'minecraft:skull'

this error might stop recipes from loading.
got any other recipe trouble apart from my items ?

**Comment by AbsolemJackdaw** [comment]
also, this modpack is killing my computer xD i dont have a performing computer, and i havent been able to walk around so far. it has just been startig up and world gen so far

**Comment by CharCharthemonkey** [comment]
none atm but cause i havent been able to fully test stuff due to issues with random crashes and such idk right off the bat

**Comment by CharCharthemonkey** [comment]
its a work in progress pack also so theres gonna be lag issues atm till i can streamline the pack

**Comment by AbsolemJackdaw** [comment]
(i have litteraly 1 fps right now)

you should start with a few mods and test their compatibility.
try to keep track of the debug launcher output as well, lots of usefull information in there.

i have found an error on my behalf though. going to try that in my dev environement and get back to you.
apperantly my necromancer skull is bot getting parsed, which might interfere with other recipes

**Comment by CharCharthemonkey** [comment]
thank you and will do

**Comment by AbsolemJackdaw** [comment]
closing issue due to age
