### ISSUE TITLE
Necromancer Minions + Gladius Lux

### ISSUE THREAD

**Issue by JuicebQx** [ArtixAllMighty/Rpg-Addon-UmbraLux#3]
Necromancer minions appear to be invisible in 1.12.2, I have tried redownloading the mods and even removing all other mods except for yours, but the minions still seem to be invisible, is there anything that might be causing this?

Edit: It would appear that the Gladius Lux when used on the ground also turns invisible.

**Comment by AbsolemJackdaw** [comment]
hmm, i might have fucked up entity registry o.O
expect a fix later today.

**Comment by AbsolemJackdaw** [comment]
solved in #ccfd5d9
